name: "RSS Feed to Markdown"
description: "Converts RSS feed entries to Markdown files"
author: "Keiran Lovett"
inputs:
  feed_url:
    description: "The URL of the RSS feed"
    required: true
  template_file:
    description: "The path to the template file"
    required: true
  output_dir:
    description: "The directory where the generated Markdown files will be saved"
    required: true
  summerize:
    description: "Summerize the Article with ChatGPT"
    required: false
  category:
    description: "categories - comma sep"
    required: false
  overwrite:
    description: "overwrite existing posts"
    required: false
  OPENAI_apiKey:
    description: "The api key for openai"
    required: false
  OPENAI_apiUrl:
    description: "The openapi url: https://api.openai.com/v1/chat/completions"
    required: false
  OPENAI_model:
    description: "The chatgpt model to use"
    required: false
  chatGPT_Prompt:
    description: "The chatgpt prompt to use"
    required: false
runs:
  using: 'node16'
  main: 'index.js'
